[package]
name = "gui_ransom"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
druid = "0.7"
webbrowser = "0.5"

[profile.dev]
opt-level = 3
# removes debugging symbols 
lto = true
